dmenu:addModifierLoader( function ()
dmenu:setRight('5',{
menuList = {
'IPv6SwitchMgr',
'macTable',
'arpTable',
'loopbackDetect',
'mirror',
'remoteMgr',
'logMgr',
'h248Auth',
'h248Basic',
'bpdu',
'routeIpv4',
'routeIpv6',
'portBinding',
'rip',
'localServiceCtrl',
'ethWanConfig',
'tunnel4in6Config',
'multicastmode',
'igmp',
'mld',
'multicastbasic',
'multicastvlan',
'multicastaddress',
'portlocate',
'voipSwithPtcl',
'voipBasic',
'voipServices',
'sipIf',
'sipAdvanced',
'sip',
'voipqos',
'fax',
'sipCallerID',
'sipslc',
'sipMedia',
'sipDigitmap',
'tunnel4in6Status',
'ponLoid',
'ponSn',
'smNetSphereMAP',
'firmwareUpgr',
'usbrestore',
'usbbackup'
},
pageList = {
{'lanMgrIpv4','Localnet_LanDevDHCPSource_t.lp'},
{'lanMgrIpv6','radhcp6s_portctrl_t.lp'}
}
})
dmenu:setRight('0',{
menuList = {
'lanMgrIpv4',
'sntp',
'parentCtrl',
'ponopticalinfo',
'firewall',
'ddns',
'filterCriteria',
'dns',
'usbfunccfg',
'samba',
'dms',
'ftp',
'dmz',
'alg',
'portForwarding',
'portTrigger',
'lanMgrIpv6',
'networkDiag',
'upnp',
'wlanAdvanced',
'wds',
'wps',
'usrCfgMgr',
},
pageList = {
{'filterCriteria','firewall_ip4filter_t.lp','firewall_ip6filter_t.lp','firewall_macfilterv3_t.lp','firewall_filterglobal_t.lp','firewall_ipfilter_t.lp','firewall_urlfilter_m.lua'},
{'localNetStatus','status_lan_info_t.lp','wlan_wlanstatus_t.lp'},
{'wlanBasic','wlan_wlanbasictogether_t.lp','wlan_wlansssidconf_t.lp','wlan_wlanbasicadconf_t.lp'},
{'accountMgr','web_login_timeout_t.lp'}
}
})
dmenu:setRight('1',{
menuList = {
'Wan3gStatus',
'tunnel6in4Status'
}
})
dmenu:removeList({
menuList = {
'l2tpStatus','l2tpConfig'
},
pageList = {
{'wlanBasic','wlan_wlansssidconflowright_t.lp'},
{'localNetStatus','wlan_wlanstatuslowright_t.lp'}
}
})
dmenu:replaceArea({
{
"routeIpv4",
"route_routestaticipv4_t.lp",
"izzi_route_routestaticipv4_t.lp"
}
})
end)
